path_training: ../../datasets/WN18/train.txt
path_output: ../../datasets/WN18/valid.txt
snapshots_at:
  - 10
  - 50
  - 100
#   - 200
#   - 500
#   - 1000
saturation: 0.99
sample_size: 500
batch_time: 1000
threshold_correct_predictions: 2
threshold_confidence: 0.00001
max_length_cylic: 3
max_length_acylic: 2
discrimination_bound: 1000
trial_size: 100000